6th_Semester/NET_Centric_Computing/Lab Codes/Practical3/Entity Framework CRUD/Models/ErrorViewModel.cs
namespace Entity_Framework_CRUD.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

6th_Semester/NET_Centric_Computing/Lab Codes/Practical3/Entity Framework CRUD/Models/Officer.cs
namespace Entity_Framework_CRUD.Models
{
    public class Officer
    {
        public Guid Id { get; set; }
        public string Name { get; set; }
        public string Gender { get; set; }
        public string Phone { get; set; }
        public string Department { get; set; }
        public string Position { get; set; }
    }
}

6th_Semester/NET_Centric_Computing/Lab Codes/Practical3/Entity Framework CRUD/Models/OfficerContext.cs
using Microsoft.EntityFrameworkCore;

namespace Entity_Framework_CRUD.Models
{
    public class OfficerContext : DbContext
    {
        public OfficerContext(DbContextOptions<OfficerContext> options) : base(options) { }

        public DbSet<Officer> tbl_officer { get; set; } // This is the table name i.e tbl_officer
    }
}

6th_Semester/NET_Centric_Computing/Lab Codes/Practical3/Entity Framework CRUD/Controllers/HomeController.cs
using Entity_Framework_CRUD.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Entity_Framework_CRUD.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

6th_Semester/NET_Centric_Computing/Lab Codes/Practical3/Entity Framework CRUD/Controllers/OfficerController.cs
using Microsoft.AspNetCore.Mvc;
using Entity_Framework_CRUD.Models;

namespace Entity_Framework_CRUD.Controllers
{
    public class OfficerController : Controller
    {
        // setting up the context class on controller
        // context class is the one that will be used to interact with the database
        private readonly OfficerContext _context;

        // constructor to initialize the context class
        public OfficerController(OfficerContext context)
        {
            _context = context;
        }

        /*
         * Read Officer method
         */
        [HttpGet]
        public IActionResult Index()
        {
            // data to be displayed in index.cshtml
            // data from the database will be converted to list and sent to view
            var officerList = _context.tbl_officer.ToList();
            return View(officerList);
        }

        /*
         * Create Officer method
         * Get and Post methods
         */
        [HttpGet]
        public IActionResult CreateOfficer()
        {
            return View();
        }

        [HttpPost]
        public IActionResult CreateOfficer(Officer o)
        {
            var officer = new Officer()
            {
                Id = Guid.NewGuid(),
                Name = o.Name,
                Gender = o.Gender,
                Department = o.Department,
                Phone = o.Phone,
                Position = o.Position
            };
            _context.tbl_officer.Add(officer);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        /*
         * Details Officer method
         * Get method
         */
        [HttpGet]
        public IActionResult GetOfficer(Guid id)
        {
            var officer = _context.tbl_officer.Find(id);
            if (officer == null)
            {
                return RedirectToAction("Index");
            }
            return View(officer);
        }

        /*
         * Update Officer method
         * Get and Post methods
         */

        /*
         * Get method to get the officer details to be updated
         */
        [HttpGet]
        public IActionResult UpdateOfficer(Guid id)
        {
            // check if the id of officer sent from view is matched with the id in the database
            // if matched, the officer details will be sent to the view
            var officer = _context.tbl_officer.FirstOrDefault(x => x.Id == id);
            if (officer == null)
            {
                return RedirectToAction("Index");
            }
            return View(officer);
        }

        /*
         * Post method to update the officer details
         */
        [HttpPost]
        public IActionResult UpdateOfficer(Officer o)
        {
            // check if the officer details are valid
            // then save the changes in database
            var officer = _context.tbl_officer.Find(o.Id);
            if (officer != null)
            {
                officer.Name = o.Name;
                officer.Gender = o.Gender;
                officer.Department = o.Department;
                officer.Phone = o.Phone;
                officer.Position = o.Position;
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }

        /*
         * Delete Officer method
         * Get and Post methods
         */

        /*
         * Get method to get the officer details to be deleted
         */
        [HttpGet]
        public IActionResult DeleteOfficer(Guid id)
        {
            // check if the id of officer sent from view is matched with the id in the database
            // if matched, the officer details will be sent to the view
            var officer = _context.tbl_officer.FirstOrDefault(x => x.Id == id);
            if (officer == null)
            {
                return RedirectToAction("Index");
            }
            return View(officer);
        }

        /*
         * Post method to delete the officer details
         */
        [HttpPost]
        public IActionResult DeleteOfficer(Officer o)
        {
            // check if the officer details are valid
            // then delete the officer from the database
            var officer = _context.tbl_officer.Find(o.Id);
            if (officer != null)
            {
                _context.tbl_officer.Remove(officer);
                _context.SaveChanges();
            }
            return RedirectToAction("Index");
        }
    }
}

6th_Semester/NET_Centric_Computing/Lab Codes/Practical3/Entity Framework CRUD/Views/Officer/CreateOfficer.cshtml
@model Entity_Framework_CRUD.Models.Officer

@{
    ViewData["Title"] = "Create Officer";
}

<h1>Create Officer</h1>

<h4>Officer</h4>
<hr />
<div>
    <div>
        <form asp-action="CreateOfficer">
            <div >
                <label asp-for="Name"></label>
                <input asp-for="Name" />
            </div>
            <div >
                <label asp-for="Gender"></label>
                <input asp-for="Gender" />
            </div>
            <div >
                <label asp-for="Phone"></label>
                <input asp-for="Phone" />
            </div>
            <div >
                <label asp-for="Department"></label>
                <input asp-for="Department" />
            </div>
            <div >
                <label asp-for="Position"></label>
                <input asp-for="Position" />
            </div>
            <div >
                <input type="submit" value="Create" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

6th_Semester/NET_Centric_Computing/Lab Codes/Practical3/Entity Framework CRUD/Views/Officer/DeleteOfficer.cshtml
@model Entity_Framework_CRUD.Models.Officer

@{
    ViewData["Title"] = "Delete Officer";
}

<h1>Delete Officer</h1>

<h4>Are you sure you want to delete this?</h4>
<hr />
<div>
    <h4>Officer</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Gender)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Gender)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Department)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Department)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Position)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Position)
        </dd>
    </dl>

    <form asp-action="DeleteOfficer">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

6th_Semester/NET_Centric_Computing/Lab Codes/Practical3/Entity Framework CRUD/Views/Officer/GetOfficer.cshtml
@model Entity_Framework_CRUD.Models.Officer;

@{
    ViewData["Title"] = "Officer Details";
}
<h1>Officer Details</h1>

<div>
    <h4>Officer</h4>
    <hr />
    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Gender</th>
                <th>Phone</th>
                <th>Department</th>
                <th>Position</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>@Model.Name</td>
                <td>@Model.Gender</td>
                <td>@Model.Phone</td>
                <td>@Model.Department</td>
                <td>@Model.Position</td>
            </tr>
        </tbody>
    </table>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

6th_Semester/NET_Centric_Computing/Lab Codes/Practical3/Entity Framework CRUD/Views/Officer/Index.cshtml
@model List<Entity_Framework_CRUD.Models.Officer>

@{
    ViewData["Title"] = "Officers List";
}

<h1>Officers List</h1>

<p>
    <a asp-action="CreateOfficer">Create New Officer</a>
</p>

<table class="table">
    <thead>
        <tr>
            <th>Name</th>
            <th>Gender</th>
            <th>Phone</th>
            <th>Department</th>
            <th>Position</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Name</td>
                <td>@item.Gender</td>
                <td>@item.Phone</td>
                <td>@item.Department</td>
                <td>@item.Position</td>
                <td>
                    <a href="Officer/GetOfficer/@item.Id">Details</a> |
                    <a href="Officer/UpdateOfficer/@item.Id">Edit</a> |
                    <a href="Officer/DeleteOfficer/@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

6th_Semester/NET_Centric_Computing/Lab Codes/Practical3/Entity Framework CRUD/Views/Officer/UpdateOfficer.cshtml
@model Entity_Framework_CRUD.Models.Officer

@{
    ViewData["Title"] = "Update Officer";
}

<h1>Update Officer</h1>

<h4>Officer</h4>
<hr />
<div>
    <form asp-action="UpdateOfficer">
        <div>
            <label asp-for="Name"></label>
            <input asp-for="Name" />
        </div>
        <div>
            <label asp-for="Gender"></label>
            <input asp-for="Gender" />
        </div>
        <div>
            <label asp-for="Phone"></label>
            <input asp-for="Phone" />
        </div>
        <div>
            <label asp-for="Department"></label>
            <input asp-for="Department" />
        </div>
        <div>
            <label asp-for="Position"></label>
            <input asp-for="Position" />
        </div>
        <div>
            <input type="submit" value="Save" />
        </div>
    </form>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

6th_Semester/NET_Centric_Computing/Lab Codes/Practical3/Entity Framework CRUD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Entity_Framework_CRUD</title>
</head>
<body>
    <header>
        <nav>
            <div>
                <a asp-controller="Home" asp-action="Index">Entity_Framework_CRUD</a>
                <button type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                </button>
                <div>
                    <ul>
                        <li>
                            <a asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li>
                            <a asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li>
                            <a asp-controller="Officer" asp-action="Index">List of Officer</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main">
            @RenderBody()
        </main>
    </div>
</body>
</html>