6th_Semester/NET_Centric_Computing/Lab Codes/Practical3/Client Side State Management/Models/ErrorViewModel.cs
namespace Client_Side_State_Management.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

6th_Semester/NET_Centric_Computing/Lab Codes/Practical3/Client Side State Management/Controllers/CookieController.cs
using Microsoft.AspNetCore.Mvc;

namespace Client_Side_State_Management.Controllers
{
    public class CookieController : Controller
    {
        /*
         * Get value from cookie 
         */
        [HttpGet]
        public IActionResult Index()
        {
            string cookieValue = Request.Cookies["Username"];
            // if cookie is present, set it to viewbag to display it on view
            if (cookieValue != null) ViewBag.Username = cookieValue;
            return View();
        }

        /*
         * Post value to set cookie which gets data from form
         */
        [HttpPost]
        public IActionResult Index(string key, string value, int? expireTime)
        {
            CookieOptions option = new CookieOptions();
            if (expireTime.HasValue)
            {
                option.Expires = DateTime.Now.AddMinutes(expireTime.Value);
            }
            else
            {
                option.Expires = DateTime.Now.AddDays(1);
            }
            Response.Cookies.Append(key, value, option);
            return RedirectToAction("Index");
        }

        /*
         * Delete cookie
         */
        public IActionResult DeleteCookie(string key)
        {
            Response.Cookies.Delete(key);
            return RedirectToAction("Index");
        }
    }
}

6th_Semester/NET_Centric_Computing/Lab Codes/Practical3/Client Side State Management/Controllers/HiddenFieldController.cs
using Microsoft.AspNetCore.Mvc;

namespace Client_Side_State_Management.Controllers
{
    public class HiddenFieldController : Controller
    {
        // logger
        private readonly ILogger<HiddenFieldController> _logger;
        public HiddenFieldController(ILogger<HiddenFieldController> logger)
        {
            _logger = logger;
        }

        /*
         * Index action method to return the view
         * Id and Name are stored in ViewBag
         */
        public IActionResult Index()
        {
            ViewBag.Id = 1;
            ViewBag.Name = "John";
            return View();
        }

        /*
         * Post action method to receive the form data
         * Id and Name are received from the form
         */
        [HttpPost]
        public IActionResult Index(int Id, string Name)
        {
            ViewBag.Id = Id;
            ViewBag.Name = Name;

            _logger.LogInformation("Id: {Id}, Name: {Name}", Id, Name); // even if the user cannot see id, it is still sent to the server
            
            return View();
        }
    }
}

6th_Semester/NET_Centric_Computing/Lab Codes/Practical3/Client Side State Management/Controllers/HomeController.cs
using Client_Side_State_Management.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace Client_Side_State_Management.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

6th_Semester/NET_Centric_Computing/Lab Codes/Practical3/Client Side State Management/Controllers/QueryStringController.cs
using Microsoft.AspNetCore.Mvc;

namespace Client_Side_State_Management.Controllers
{
    public class QueryStringController : Controller
    {
        public IActionResult Index(string name, string age)
        {
            ViewBag.Name = name;
            ViewBag.Age = age;
            return View();
        }
    }
}

6th_Semester/NET_Centric_Computing/Lab Codes/Practical3/Client Side State Management/Views/HiddenField/Index.cshtml
@{
    ViewData["Title"] = "HiddenField for Client-Side State Management";
}

<h1>@ViewData["Title"]</h1>

<form asp-action="Index" method="post">
    <input type="hidden" id="Id" name="Id" value="@ViewBag.Id" />
    <label for="Name">Name:</label>
    <input type="text" id="Name" name="Name" value="@ViewBag.Name" />
    <button type="submit">Submit</button>
</form>

6th_Semester/NET_Centric_Computing/Lab Codes/Practical3/Client Side State Management/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Client Side State Management</title>
</head>
<body>
    <header>
        <nav>
            <ul>
                <li>
                    <a asp-controller="Home" asp-action="Index">Home</a>
                </li>
                <li>
                    <a asp-controller="Cookie" asp-action="Index">Cookie</a>
                </li>
                <li>
                    <a asp-controller="QueryString" asp-action="Index">Query Strings</a>
                </li>
                <li>
                    <a asp-controller="HiddenField" asp-action="Index">Hidden Field</a>
                </li>
            </ul>
        </nav>
    </header>
    <div>
        <main role="main">
            @RenderBody()
        </main>
    </div>
</body>
</html>